language: python

python:
  - "3.6"

install:
  - pip install pytest hypothesis

script:
  - cd test
  - bash run-tests.sh
  - cd ../v03
  - PYTHONPATH=. pytest test
  - cd ../v04/zaweb
  - pip install ".[test]"
  - PYTHONPATH=../zorkalike:. pytest test
